language: java
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - ./gradlew clean check build 
  - ./gradlew clean fatJar 
  - ./dependency.sh
  - ./rec src/test/resources/test.js
  - ./rec dump src/test/resources/caching.bin.test 3
  - psql -f example/script/test.sql test -U postgres
  - ./rec example/db.js
